spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3308/test_app?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
boot:
  jwt:
    issuer: yotsuki
    expirationMs: 30000000
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

logging:
  level:
    org.springframework.web: DEBUG