spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://45.144.167.216:3306/db_novel_shop?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Su%dhQ&wYFx*V8K%
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
boot:
  jwt:
    issuer: yotsuki
    expirationMs: 18748800000
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8080